# 1140621
https://www.perplexity.ai/search/045ecda7-23bf-4d76-9155-fcb886e2425e

In [2]:
%pip install numpy
import numpy as np
np.random.random()
np.random.random(3)
np.random.random(size=3)
np.random.random((3, 4))
np.random.random(size=(3,4))

Note: you may need to restart the kernel to use updated packages.


array([[0.39033499, 0.09273411, 0.36326074, 0.13329817],
       [0.58863667, 0.61986335, 0.8190668 , 0.54682429],
       [0.02794285, 0.63653684, 0.40984427, 0.38317992]])

In [3]:
from numpy.random import normal 

normal_value = normal(size=(3, 4))
#ndarray常用的實體屬性
type(normal_value)
normal_value.ndim
normal_value.size
normal_value.shape
normal_value.dtype

dtype('float64')

In [4]:
#ndarray,陣列運算
normal_value * 10

array([[ -2.37222518, -23.56457407,  17.42447013,  13.84793416],
       [ -6.68152112, -14.40061839,  -9.65816043,  11.68811843],
       [  8.43901649, -12.17893942,  -5.90347133,   4.38563009]])

In [5]:
#ndarray,的統計
normal_value.sum()
normal_value.sum(axis=0)
normal_value.sum(axis=1)

array([ 0.5335605 , -1.90521815, -0.52577642])